/* listview.c generated by valac 0.9.8, the Vala compiler
 * generated from listview.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define COMPONENTS_TYPE_LIST_VIEW (components_list_view_get_type ())
#define COMPONENTS_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), COMPONENTS_TYPE_LIST_VIEW, ComponentsListView))
#define COMPONENTS_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), COMPONENTS_TYPE_LIST_VIEW, ComponentsListViewClass))
#define COMPONENTS_IS_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), COMPONENTS_TYPE_LIST_VIEW))
#define COMPONENTS_IS_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), COMPONENTS_TYPE_LIST_VIEW))
#define COMPONENTS_LIST_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), COMPONENTS_TYPE_LIST_VIEW, ComponentsListViewClass))

typedef struct _ComponentsListView ComponentsListView;
typedef struct _ComponentsListViewClass ComponentsListViewClass;
typedef struct _ComponentsListViewPrivate ComponentsListViewPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define COMPONENTS_TYPE_DIRECTORY_MODEL (components_directory_model_get_type ())
#define COMPONENTS_DIRECTORY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), COMPONENTS_TYPE_DIRECTORY_MODEL, ComponentsDirectoryModel))
#define COMPONENTS_DIRECTORY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), COMPONENTS_TYPE_DIRECTORY_MODEL, ComponentsDirectoryModelClass))
#define COMPONENTS_IS_DIRECTORY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), COMPONENTS_TYPE_DIRECTORY_MODEL))
#define COMPONENTS_IS_DIRECTORY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), COMPONENTS_TYPE_DIRECTORY_MODEL))
#define COMPONENTS_DIRECTORY_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), COMPONENTS_TYPE_DIRECTORY_MODEL, ComponentsDirectoryModelClass))

typedef struct _ComponentsDirectoryModel ComponentsDirectoryModel;
typedef struct _ComponentsDirectoryModelClass ComponentsDirectoryModelClass;

#define COMPONENTS_TYPE_MY_MODEL (components_my_model_get_type ())
#define COMPONENTS_MY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), COMPONENTS_TYPE_MY_MODEL, ComponentsMyModel))
#define COMPONENTS_MY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), COMPONENTS_TYPE_MY_MODEL, ComponentsMyModelClass))
#define COMPONENTS_IS_MY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), COMPONENTS_TYPE_MY_MODEL))
#define COMPONENTS_IS_MY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), COMPONENTS_TYPE_MY_MODEL))
#define COMPONENTS_MY_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), COMPONENTS_TYPE_MY_MODEL, ComponentsMyModelClass))

typedef struct _ComponentsMyModel ComponentsMyModel;
typedef struct _ComponentsMyModelClass ComponentsMyModelClass;

struct _ComponentsListView {
	GtkTreeView parent_instance;
	ComponentsListViewPrivate * priv;
};

struct _ComponentsListViewClass {
	GtkTreeViewClass parent_class;
};


static gpointer components_list_view_parent_class = NULL;

GType components_list_view_get_type (void) G_GNUC_CONST;
enum  {
	COMPONENTS_LIST_VIEW_DUMMY_PROPERTY
};
static GtkTreeViewColumn* components_list_view_create_text_column (ComponentsListView* self, const char* name, gint model_index, float xalign);
static GtkTreeViewColumn* components_list_view_create_name_column (ComponentsListView* self, const char* name, gint model_index_icon, gint model_index_name);
ComponentsListView* components_list_view_new (void);
ComponentsListView* components_list_view_construct (GType object_type);
ComponentsMyModel* components_my_model_new (void);
ComponentsMyModel* components_my_model_construct (GType object_type);
GType components_directory_model_get_type (void) G_GNUC_CONST;
GType components_my_model_get_type (void) G_GNUC_CONST;
static GObject * components_list_view_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);



static GtkTreeViewColumn* components_list_view_create_text_column (ComponentsListView* self, const char* name, gint model_index, float xalign) {
	GtkTreeViewColumn* result = NULL;
	GtkCellRendererText* renderer_text;
	GValue _tmp0_ = {0};
	GValue _tmp1_;
	GtkTreeViewColumn* column;
	GValue _tmp2_ = {0};
	GValue _tmp3_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	renderer_text = g_object_ref_sink ((GtkCellRendererText*) gtk_cell_renderer_text_new ());
	g_object_set_property ((GObject*) renderer_text, "xalign", (_tmp1_ = (g_value_init (&_tmp0_, G_TYPE_FLOAT), g_value_set_float (&_tmp0_, xalign), _tmp0_), &_tmp1_));
	column = g_object_ref_sink (gtk_tree_view_column_new ());
	g_object_set_property ((GObject*) column, "alignment", (_tmp3_ = (g_value_init (&_tmp2_, G_TYPE_FLOAT), g_value_set_float (&_tmp2_, xalign), _tmp2_), &_tmp3_));
	gtk_tree_view_column_set_title (column, name);
	gtk_cell_layout_pack_start ((GtkCellLayout*) column, (GtkCellRenderer*) renderer_text, TRUE);
	gtk_cell_layout_add_attribute ((GtkCellLayout*) column, (GtkCellRenderer*) renderer_text, "text", model_index);
	result = column;
	_g_object_unref0 (renderer_text);
	return result;
}


static GtkTreeViewColumn* components_list_view_create_name_column (ComponentsListView* self, const char* name, gint model_index_icon, gint model_index_name) {
	GtkTreeViewColumn* result = NULL;
	GtkCellRendererText* renderer_text;
	GtkCellRendererPixbuf* renderer_icon;
	GtkTreeViewColumn* column;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	renderer_text = g_object_ref_sink ((GtkCellRendererText*) gtk_cell_renderer_text_new ());
	renderer_icon = g_object_ref_sink ((GtkCellRendererPixbuf*) gtk_cell_renderer_pixbuf_new ());
	column = g_object_ref_sink (gtk_tree_view_column_new ());
	gtk_tree_view_column_set_expand (column, TRUE);
	gtk_tree_view_column_set_title (column, name);
	gtk_cell_layout_pack_start ((GtkCellLayout*) column, (GtkCellRenderer*) renderer_icon, FALSE);
	gtk_cell_layout_pack_start ((GtkCellLayout*) column, (GtkCellRenderer*) renderer_text, TRUE);
	gtk_cell_layout_add_attribute ((GtkCellLayout*) column, (GtkCellRenderer*) renderer_text, "text", model_index_name);
	gtk_cell_layout_add_attribute ((GtkCellLayout*) column, (GtkCellRenderer*) renderer_icon, "pixbuf", model_index_icon);
	result = column;
	_g_object_unref0 (renderer_icon);
	_g_object_unref0 (renderer_text);
	return result;
}


ComponentsListView* components_list_view_construct (GType object_type) {
	ComponentsListView * self;
	self = g_object_newv (object_type, 0, NULL);
	return self;
}


ComponentsListView* components_list_view_new (void) {
	return components_list_view_construct (COMPONENTS_TYPE_LIST_VIEW);
}


static GObject * components_list_view_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ComponentsListView * self;
	parent_class = G_OBJECT_CLASS (components_list_view_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = COMPONENTS_LIST_VIEW (obj);
	{
		ComponentsMyModel* store;
		GtkTreeModelFilter* filter;
		GtkTreeViewColumn* _tmp0_;
		GtkTreeViewColumn* _tmp1_;
		GtkTreeViewColumn* _tmp2_;
		store = components_my_model_new ();
		filter = (GtkTreeModelFilter*) gtk_tree_model_filter_new ((GtkTreeModel*) store, NULL);
		gtk_tree_view_set_model ((GtkTreeView*) self, (GtkTreeModel*) filter);
		gtk_tree_view_append_column ((GtkTreeView*) self, _tmp0_ = components_list_view_create_name_column (self, "Name", 0, 1));
		_g_object_unref0 (_tmp0_);
		gtk_tree_view_append_column ((GtkTreeView*) self, _tmp1_ = components_list_view_create_text_column (self, "Size", 2, 1.0f));
		_g_object_unref0 (_tmp1_);
		gtk_tree_view_append_column ((GtkTreeView*) self, _tmp2_ = components_list_view_create_text_column (self, "Modified", 2, 1.0));
		_g_object_unref0 (_tmp2_);
		_g_object_unref0 (filter);
		_g_object_unref0 (store);
	}
	return obj;
}


static void components_list_view_class_init (ComponentsListViewClass * klass) {
	components_list_view_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->constructor = components_list_view_constructor;
}


static void components_list_view_instance_init (ComponentsListView * self) {
}


GType components_list_view_get_type (void) {
	static volatile gsize components_list_view_type_id__volatile = 0;
	if (g_once_init_enter (&components_list_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ComponentsListViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) components_list_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ComponentsListView), 0, (GInstanceInitFunc) components_list_view_instance_init, NULL };
		GType components_list_view_type_id;
		components_list_view_type_id = g_type_register_static (GTK_TYPE_TREE_VIEW, "ComponentsListView", &g_define_type_info, 0);
		g_once_init_leave (&components_list_view_type_id__volatile, components_list_view_type_id);
	}
	return components_list_view_type_id__volatile;
}




