
package service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ShopService", targetNamespace = "http://service/", wsdlLocation = "http://myhost:8080/ShopService/ServerOperations?wsdl")
public class ShopService
    extends Service
{

    private final static URL SHOPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(service.ShopService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = service.ShopService.class.getResource(".");
            url = new URL(baseUrl, "http://myhost:8080/ShopService/ServerOperations?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://myhost:8080/ShopService/ServerOperations?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SHOPSERVICE_WSDL_LOCATION = url;
    }

    public ShopService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShopService() {
        super(SHOPSERVICE_WSDL_LOCATION, new QName("http://service/", "ShopService"));
    }

    /**
     * 
     * @return
     *     returns SOI
     */
    @WebEndpoint(name = "ServerOperationsPort")
    public SOI getServerOperationsPort() {
        return super.getPort(new QName("http://service/", "ServerOperationsPort"), SOI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOI
     */
    @WebEndpoint(name = "ServerOperationsPort")
    public SOI getServerOperationsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "ServerOperationsPort"), SOI.class, features);
    }

}
